# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Champion.create!(name: "Aatrox", image: 'img/champions/AatroxSquare.png', description: 'The Darkin Blade', category_id: champion.id, list_id: '')
Champion.create!(name: "Ahri", image: 'img/champions/AhriSquare.png', description: 'The Nine-Tailed Fox', category_id: champion.id, list_id: '')
Champion.create!(name: "Akali", image: 'img/champions/AkaliSquare.png', description: 'The Rouge Assassin', category_id: champion.id, list_id: '')
Champion.create!(name: "Alistar", image: 'img/champions/AlistarSquare.png', description: 'The Minotaur', category_id: champion.id, list_id: '')
Champion.create!(name: "Amumu", image: 'img/champions/AmumuSquare.png', description: 'The Sad Mummy', category_id: champion.id, list_id: '')
Champion.create!(name: "Anivia", image: 'img/champions/AniviaSquare.png', description: 'The Cryophoenix', category_id: champion.id, list_id: '')
Champion.create!(name: "Annie", image: 'img/champions/AnnieSquare.png', description: 'The Dark Child', category_id: champion.id, list_id: '')
Champion.create!(name: "Aphelios", image: 'img/champions/ApheliosSquare.png', description: 'The Weapon of the Faithful', category_id: champion.id, list_id: '')
Champion.create!(name: "Ashe", image: 'img/champions/AsheSquare.png', description: 'The Frost Archer', category_id: champion.id, list_id: '')
Champion.create!(name: "Aurelion Sol", image: 'img/champions/Aurelion_SolSquare.png', description: 'The Star Forger', category_id: champion.id, list_id: '')

Champion.create!(name: "Azir", image: 'img/champions/AzirSquare.png', description: 'The Emperor of the Sands', category_id: champion.id, list_id: '')
Champion.create!(name: "Bard", image: 'img/champions/BardSquare.png', description: 'The Wandering Caretaker', category_id: champion.id, list_id: '')
Champion.create!(name: "Blitzcrank", image: 'img/champions/BlitzcrankSquare.png', description: 'The Great Steam Golem', category_id: champion.id, list_id: '')
Champion.create!(name: "Brand", image: 'img/champions/BrandSquare.png', description: 'The Burning Vengeance', category_id: champion.id, list_id: '')
Champion.create!(name: "Braum", image: 'img/champions/BraumSquare.png', description: 'The Heart of the Freljord', category_id: champion.id, list_id: '')
Champion.create!(name: "Caitlyn", image: 'img/champions/CaitlynSquare.png', description: 'The Sheriff of Piltover', category_id: champion.id, list_id: '')
Champion.create!(name: "Camille", image: 'img/champions/CamilleSquare.png', description: 'The Steel Shadow', category_id: champion.id, list_id: '')
Champion.create!(name: "Cassiopeia", image: 'img/champions/CassiopeiaSquare.png', description: 'The Serpents Embrace', category_id: champion.id, list_id: '')
Champion.create!(name: "Cho'Gath", image: 'img/champions/ChoGathSquare.png', description: 'The Terror of the Void', category_id: champion.id, list_id: '')
Champion.create!(name: "Corki", image: 'img/champions/CorkiSquare.png', description: 'The Daring Bombardier', category_id: champion.id, list_id: '')

Champion.create!(name: "Darius", image: 'img/champions/DariusSquare.png', description: 'The Hand of Noxas', category_id: champion.id, list_id: '')
Champion.create!(name: "Diana", image: 'img/champions/DianaSquare.png', description: 'The Scorn of the Moon', category_id: champion.id, list_id: '')
Champion.create!(name: "Dr. Mundo", image: 'img/champions/Dr._MundoSquare.png', description: 'The Madman of Zaun', category_id: champion.id, list_id: '')
Champion.create!(name: "Draven", image: 'img/champions/DravenSquare.png', description: 'The Glorious Executioner', category_id: champion.id, list_id: '')
Champion.create!(name: "Ekko", image: 'img/champions/EkkoSquare.png', description: 'The Boy Who Shattered Time', category_id: champion.id, list_id: '')
Champion.create!(name: "Elise", image: 'img/champions/EliseSquare.png', description: 'The Spider Queen', category_id: champion.id, list_id: '')
Champion.create!(name: "Evelynn", image: 'img/champions/EvelynnSquare.png', description: 'Agonys Embrace', category_id: champion.id, list_id: '')
Champion.create!(name: "Ezreal", image: 'img/champions/EzrealSquare.png', description: 'The Prodigal Explorer', category_id: champion.id, list_id: '')
Champion.create!(name: "Fiddlesticks", image: 'img/champions/FiddlesticksSquare.png', description: 'The Ancient Fear', category_id: champion.id, list_id: '')
Champion.create!(name: "Fiora", image: 'img/champions/FioraSquare.png', description: 'The Grand Duelist', category_id: champion.id, list_id: '')

Champion.create!(name: "Fizz", image: 'img/champions/FizzSquare.png', description: 'The Tidal Trickster', category_id: champion.id, list_id: '')
Champion.create!(name: "Galio", image: 'img/champions/GalioSquare.png', description: 'The Colossus', category_id: champion.id, list_id: '')
Champion.create!(name: "Gangplank", image: 'img/champions/GangplankSquare.png', description: 'The Saltwater Scourg', category_id: champion.id, list_id: '')
Champion.create!(name: "Garen", image: 'img/champions/GarenSquare.png', description: 'The Might of Demacia', category_id: champion.id, list_id: '')
Champion.create!(name: "Gnar", image: 'img/champions/GnarSquare.png', description: 'The Missing Link', category_id: champion.id, list_id: '')
Champion.create!(name: "Gragas", image: 'img/champions/GragasSquare.png', description: 'The Rabble Rouser', category_id: champion.id, list_id: '')
Champion.create!(name: "Graves", image: 'img/champions/GravesSquare.png', description: 'The Outlaw', category_id: champion.id, list_id: '')
Champion.create!(name: "Hecarim", image: 'img/champions/HecarimSquare.png', description: 'The Shadow of War', category_id: champion.id, list_id: '')
Champion.create!(name: "Heimerdinger", image: 'img/champions/HeimerdingerSquare_Unreleased.png', description: 'The Revered Inventor', category_id: champion.id, list_id: '')
Champion.create!(name: "Illaoi", image: 'img/champions/IllaoiSquare.png', description: 'The Kraken Priestess', category_id: champion.id, list_id: '')

Champion.create!(name: "Irelia", image: 'img/champions/IreliaSquare.png', description: 'The Blade Dancer', category_id: champion.id, list_id: '')
Champion.create!(name: "Ivern", image: 'img/champions/IvernSquare.png', description: 'The Green Father', category_id: champion.id, list_id: '')
Champion.create!(name: "Janna", image: 'img/champions/JannaSquare.png', description: 'The Storms Fury', category_id: champion.id, list_id: '')
Champion.create!(name: "Jarvan IV", image: 'img/champions/Jarvan_IVSquare.png', description: 'The Exemplar of Demacia', category_id: champion.id, list_id: '')
Champion.create!(name: "Jax", image: 'img/champions/JaxSquare.png', description: 'The Grandmaster at Arms', category_id: champion.id, list_id: '')
Champion.create!(name: "Jayce", image: 'img/champions/JayceSquare.png', description: 'The Defender of Tomorrow', category_id: champion.id, list_id: '')
Champion.create!(name: "Jhin", image: 'img/champions/JhinSquare.png', description: 'The Virtuoso', category_id: champion.id, list_id: '')
Champion.create!(name: "Jinx", image: 'img/champions/JinxSquare.png', description: 'The Loose Cannon', category_id: champion.id, list_id: '')
Champion.create!(name: "Kai'Sa", image: 'img/champions/KaiSaSquare.png', description: 'Daughter of the Void', category_id: champion.id, list_id: '')
Champion.create!(name: "Kalista", image: 'img/champions/KalistaSquare.png', description: 'The Spear of Vengeance', category_id: champion.id, list_id: '')

Champion.create!(name: "Karma", image: 'img/champions/KarmaSquare.png', description: 'The Enlightened One', category_id: champion.id, list_id: '')
Champion.create!(name: "Karthus", image: 'img/champions/KarthusSquare.png', description: 'The Deathsinger', category_id: champion.id, list_id: '')
Champion.create!(name: "Kassadin", image: 'img/champions/KassadinSquare.png', description: 'The Void Walker', category_id: champion.id, list_id: '')
Champion.create!(name: "Katarina", image: 'img/champions/KatarinaSquare.png', description: 'The Sinister Blade', category_id: champion.id, list_id: '')
Champion.create!(name: "Kayle", image: 'img/champions/KayleSquare.png', description: 'The Righteous', category_id: champion.id, list_id: '')
Champion.create!(name: "Kayn", image: 'img/champions/KaynSquare.png', description: 'The Shadow Reaper', category_id: champion.id, list_id: '')
Champion.create!(name: "Kennen", image: 'img/champions/KennenSquare.png', description: 'The Heart of the Tempest', category_id: champion.id, list_id: '')
Champion.create!(name: "Kha'Zix", image: 'img/champions/KhaZixSquare.png', description: 'The Voidreaver', category_id: champion.id, list_id: '')
Champion.create!(name: "Kindred", image: 'img/champions/KindredSquare.png', description: 'The Eternal Hunters', category_id: champion.id, list_id: '')
Champion.create!(name: "Kled", image: 'img/champions/KledSquare.png', description: 'The Cantankerous Cavalier', category_id: champion.id, list_id: '')

Champion.create!(name: "Kog'Maw", image: 'img/champions/KogMawSquare.png', description: 'The Mouth of the Abyss', category_id: champion.id, list_id: '')
Champion.create!(name: "LeBlanc", image: 'img/champions/LeBlancSquare.png', description: 'The Deceiver', category_id: champion.id, list_id: '')
Champion.create!(name: "Lee Sin", image: 'img/champions/Lee_SinSquare.png', description: 'The Blind Monk', category_id: champion.id, list_id: '')
Champion.create!(name: "Leona", image: 'img/champions/LeonaSquare.png', description: 'The Radiant Dawn', category_id: champion.id, list_id: '')
Champion.create!(name: "Lillia", image: 'img/champions/LilliaSquare.png', description: 'The Bashful Bloom', category_id: champion.id, list_id: '')
Champion.create!(name: "Lissandra", image: 'img/champions/LissandraSquare.png', description: 'The Ice Witch', category_id: champion.id, list_id: '')
Champion.create!(name: "Lucian", image: 'img/champions/LucianSquare.png', description: 'The Purifier', category_id: champion.id, list_id: '')
Champion.create!(name: "Lulu", image: 'img/champions/LuluSquare.png', description: 'The Fae Sorceress', category_id: champion.id, list_id: '')
Champion.create!(name: "Lux", image: 'img/champions/LuxSquare.png', description: 'The Lady of Luminosity', category_id: champion.id, list_id: '')
Champion.create!(name: "Malphite", image: 'img/champions/MalphiteSquare.png', description: 'Shard of the Monolith', category_id: champion.id, list_id: '')

Champion.create!(name: "Malzahar", image: 'img/champions/MalzaharSquare.png', description: 'The Prophet of the Void', category_id: champion.id, list_id: '')
Champion.create!(name: "Maokai", image: 'img/champions/MaokaiSquare.png', description: 'The Twisted Treant', category_id: champion.id, list_id: '')
Champion.create!(name: "Master Yi", image: 'img/champions/Master_YiSquare.png', description: 'The Wuju Bladesman', category_id: champion.id, list_id: '')
Champion.create!(name: "Miss Fortune", image: 'img/champions/MissFortuneSquare.png', description: 'The Bounty Hunter', category_id: champion.id, list_id: '')
Champion.create!(name: "Mordekaiser", image: 'img/champions/MordekaiserSquare.png', description: 'The Iron Revenant', category_id: champion.id, list_id: '')
Champion.create!(name: "Morgana", image: 'img/champions/MorganaSquare.png', description: 'The Fallen', category_id: champion.id, list_id: '')
Champion.create!(name: "Nami", image: 'img/champions/NamiSquare.png', description: 'The Tidecaller', category_id: champion.id, list_id: '')
Champion.create!(name: "Nasus", image: 'img/champions/NasusSquare.png', description: 'The Curator of the Sands', category_id: champion.id, list_id: '')
Champion.create!(name: "Nautilus", image: 'img/champions/NautilusSquare.png', description: 'The Titan of the Depths', category_id: champion.id, list_id: '')
Champion.create!(name: "Neeko", image: 'img/champions/NeekoSquare.png', description: 'The Curious Chameleon', category_id: champion.id, list_id: '')

Champion.create!(name: "Nidalee", image: 'img/champions/NidaleeSquare.png', description: 'The Bestial Huntress', category_id: champion.id, list_id: '')
Champion.create!(name: "Nocturne", image: 'img/champions/NocturneSquare.png', description: 'The Eternal Nightmare', category_id: champion.id, list_id: '')
Champion.create!(name: "Nunu & Willump", image: 'img/champions/NunuWillumpSquare.png', description: 'The Boy and His Yeti', category_id: champion.id, list_id: '')
Champion.create!(name: "Olaf", image: 'img/champions/OlafSquare.png', description: 'The Berserker', category_id: champion.id, list_id: '')
Champion.create!(name: "Orianna", image: 'img/champions/OriannaSquare.png', description: 'The Lady of Clockwork', category_id: champion.id, list_id: '')
Champion.create!(name: "Ornn", image: 'img/champions/OrnnSquare.png', description: 'The Fire Below the Mountain', category_id: champion.id, list_id: '')
Champion.create!(name: "Pantheon", image: 'img/champions/PantheonSquare.png', description: 'The Unbreakable Spear', category_id: champion.id, list_id: '')
Champion.create!(name: "Poppy", image: 'img/champions/PoppySquare.png', description: 'Keeper of the Hammer', category_id: champion.id, list_id: '')
Champion.create!(name: "Pyke", image: 'img/champions/PykeSquare.png', description: 'The Bloodharbor Ripper', category_id: champion.id, list_id: '')
Champion.create!(name: "Qiyana", image: 'img/champions/QiyanaSquare.png', description: 'Empress of the Elements', category_id: champion.id, list_id: '')

Champion.create!(name: "Quinn", image: 'img/champions/QuinnSquare.png', description: 'Demacias Wings', category_id: champion.id, list_id: '')
Champion.create!(name: "Rakan", image: 'img/champions/RakanSquare.png', description: 'The Charmer', category_id: champion.id, list_id: '')
Champion.create!(name: "Rammus", image: 'img/champions/RammusSquare.png', description: 'The Armordillo', category_id: champion.id, list_id: '')
Champion.create!(name: "Rek'Sai", image: 'img/champions/RekSaiSquare.png', description: 'The Void Burrower', category_id: champion.id, list_id: '')
Champion.create!(name: "Renekton", image: 'img/champions/RenektonSquare.png', description: 'The Butcher of the Sands', category_id: champion.id, list_id: '')
Champion.create!(name: "Rengar", image: 'img/champions/RengarSquare.png', description: 'The Pridestalker', category_id: champion.id, list_id: '')
Champion.create!(name: "Riven", image: 'img/champions/RivenSquare.png', description: 'The Exile', category_id: champion.id, list_id: '')
Champion.create!(name: "Rumble", image: 'img/champions/RumbleSquare.png', description: 'The Mechanized Menace', category_id: champion.id, list_id: '')
Champion.create!(name: "Ryze", image: 'img/champions/RyzeSquare.png', description: 'The Rune Mage', category_id: champion.id, list_id: '')
Champion.create!(name: "Samira", image: 'img/champions/SamiraSquare.png', description: 'The Desert Rose', category_id: champion.id, list_id: '')

Champion.create!(name: "Sejuani", image: 'img/champions/SejuaniSquare.png', description: 'Fury of the North', category_id: champion.id, list_id: '')
Champion.create!(name: "Senna", image: 'img/champions/SennaSquare.png', description: 'The Redeemer', category_id: champion.id, list_id: '')
Champion.create!(name: "Seraphine", image: 'img/champions/SeraphineSquare.png', description: 'The Starry-Eyed Songstress', category_id: champion.id, list_id: '')
Champion.create!(name: "Sett", image: 'img/champions/SettSquare.png', description: 'The Boss', category_id: champion.id, list_id: '')
Champion.create!(name: "Shaco", image: 'img/champions/ShacoSquare.png', description: 'The Demon Jester', category_id: champion.id, list_id: '')
Champion.create!(name: "Shen", image: 'img/champions/ShenSquare.png', description: 'The Eye of Twilight', category_id: champion.id, list_id: '')
Champion.create!(name: "Shyvana", image: 'img/champions/ShyvanaSquare.png', description: 'The Half-Dragon', category_id: champion.id, list_id: '')
Champion.create!(name: "Singed", image: 'img/champions/SingedSquare.png', description: 'The Mad Chemist', category_id: champion.id, list_id: '')
Champion.create!(name: "Sion", image: 'img/champions/SionSquare.png', description: 'The Undead Juggernaut', category_id: champion.id, list_id: '')
Champion.create!(name: "Sivir", image: 'img/champions/SivirSquare.png', description: 'The Battle Mistress', category_id: champion.id, list_id: '')

Champion.create!(name: "Skarner", image: 'img/champions/SkarnerSquare.png', description: 'The Crystal Vanguard', category_id: champion.id, list_id: '')
Champion.create!(name: "Sona", image: 'img/champions/SonaSquare.png', description: 'Maven of Strings', category_id: champion.id, list_id: '')
Champion.create!(name: "Soraka", image: 'img/champions/SorakaSquare.png', description: 'The Starchild', category_id: champion.id, list_id: '')
Champion.create!(name: "Swain", image: 'img/champions/SwainSquare.png', description: 'The Noxian Grand General', category_id: champion.id, list_id: '')
Champion.create!(name: "Sylas", image: 'img/champions/SylasSquare.png', description: 'The Unshackled', category_id: champion.id, list_id: '')
Champion.create!(name: "Syndra", image: 'img/champions/SyndraSquare.png', description: 'The Dark Sovereign', category_id: champion.id, list_id: '')
Champion.create!(name: "Tahm Kench", image: 'img/champions/Tahm_KenchSquare.png', description: 'The River King', category_id: champion.id, list_id: '')
Champion.create!(name: "Taliyah", image: 'img/champions/TaliyahSquare.png', description: 'The Stoneweaver', category_id: champion.id, list_id: '')
Champion.create!(name: "Talon", image: 'img/champions/TalonSquare.png', description: 'The Blades Shadow', category_id: champion.id, list_id: '')
Champion.create!(name: "Taric", image: 'img/champions/TaricSquare.png', description: 'The Sheild of Valoran', category_id: champion.id, list_id: '')

Champion.create!(name: "Teemo", image: 'img/champions/TeemoSquare.png', description: 'The Swift Scout', category_id: champion.id, list_id: '')
Champion.create!(name: "Thresh", image: 'img/champions/ThreshSquare.png', description: 'The Chain Warden', category_id: champion.id, list_id: '')
Champion.create!(name: "Tristana", image: 'img/champions/TristanaSquare.png', description: 'The Yordle Gunner', category_id: champion.id, list_id: '')
Champion.create!(name: "Trundle", image: 'img/champions/TrundleSquare.png', description: 'The Troll King', category_id: champion.id, list_id: '')
Champion.create!(name: "Tryndamere", image: 'img/champions/TryndamereSquare.png', description: 'The Barbarian King', category_id: champion.id, list_id: '')
Champion.create!(name: "Twisted Fate", image: 'img/champions/Twisted_FateSquare.png', description: 'The Card Master', category_id: champion.id, list_id: '')
Champion.create!(name: "Twitch", image: 'img/champions/TwitchSquare.png', description: 'The Plague Rat', category_id: champion.id, list_id: '')
Champion.create!(name: "Udyr", image: 'img/champions/UdyrSquare.png', description: 'The Spirit Walker', category_id: champion.id, list_id: '')
Champion.create!(name: "Urgot", image: 'img/champions/UrgotSquare.png', description: 'The Dreadnought', category_id: champion.id, list_id: '')
Champion.create!(name: "Varus", image: 'img/champions/VarusSquare.png', description: 'The Arrow of Retribution', category_id: champion.id, list_id: '')

Champion.create!(name: "Vayne", image: 'img/champions/VayneSquare.png', description: 'The Night Hunter', category_id: champion.id, list_id: '')
Champion.create!(name: "Veigar", image: 'img/champions/VeigarSquare.png', description: 'The Tiny Master of Evil', category_id: champion.id, list_id: '')
Champion.create!(name: "Vel'Koz", image: 'img/champions/VelKozSquare.png', description: 'The Eye of the Void', category_id: champion.id, list_id: '')
Champion.create!(name: "Vi", image: 'img/champions/ViSquare.png', description: 'The Piltover Enforcer', category_id: champion.id, list_id: '')
Champion.create!(name: "Viktor", image: 'img/champions/ViktorSquare.png', description: 'The Machine Herald', category_id: champion.id, list_id: '')
Champion.create!(name: "Vladimir", image: 'img/champions/VladimirSquare.png', description: 'The Crimson Reaper', category_id: champion.id, list_id: '')
Champion.create!(name: "Volibear", image: 'img/champions/VolibearSquare.png', description: 'The Relentless Storm', category_id: champion.id, list_id: '')
Champion.create!(name: "Warwick", image: 'img/champions/WarwickSquare.png', description: 'The Uncaged Wrath of Zaun', category_id: champion.id, list_id: '')
Champion.create!(name: "Wukong", image: 'img/champions/WukongSquare.png', description: 'The Monkey King', category_id: champion.id, list_id: '')
Champion.create!(name: "Xayah", image: 'img/champions/XayahSquare.png', description: 'The Rebel', category_id: champion.id, list_id: '')

Champion.create!(name: "Xerath", image: 'img/champions/XerathSquare.png', description: 'The Magus Ascendant', category_id: champion.id, list_id: '')
Champion.create!(name: "Xin Zhao", image: 'img/champions/Xin_ZhaoSquare.png', description: 'The Seneschal of Demacia', category_id: champion.id, list_id: '')
Champion.create!(name: "Yasuo", image: 'img/champions/YasuoSquare.png', description: 'The Unforgiven', category_id: champion.id, list_id: '')
Champion.create!(name: "Yone", image: 'img/champions/YoneSquare.png', description: 'The Unforgotten', category_id: champion.id, list_id: '')
Champion.create!(name: "Yorick", image: 'img/champions/YorickSquare.png', description: 'Shepherd of Souls', category_id: champion.id, list_id: '')
Champion.create!(name: "Yuumi", image: 'img/champions/YuumiSquare.png', description: 'The Magical Cat', category_id: champion.id, list_id: '')
Champion.create!(name: "Zac", image: 'img/champions/ZacSquare.png', description: 'The Secret Weapon', category_id: champion.id, list_id: '')
Champion.create!(name: "Zed", image: 'img/champions/ZedSquare.png', description: 'The Master of Shadows', category_id: champion.id, list_id: '')
Champion.create!(name: "Ziggs", image: 'img/champions/ZiggsSquare.png', description: 'The Hexplosives Expert', category_id: champion.id, list_id: '')
Champion.create!(name: "Zilean", image: 'img/champions/ZileanSquare.png', description: 'The Chronokeeper', category_id: champion.id, list_id: '')

Champion.create!(name: "Zoe", image: 'img/champions/ZoeSquare.png', description: 'The Aspect of Twilight', category_id: champion.id, list_id: '')
Champion.create!(name: "Zyra", image: 'img/champions/ZyraSquare.png', description: 'Rise of the Thorns', category_id: champion.id, list_id: '')

